---
- name: catalogue configuration
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      system: true
      shell: /sbin/nologin
      home: /app
##Remove directory
  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

##create a dir
  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete catalogue file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent


  - name: Download file to destination
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip 
  
  - name: extract catalogue zip
    ansible.builtin.unarchive:
      dest: /app
      src: /tmp/catalogue.zip
      remote_src: yes

  - name: node js install
    community.genral.npm:
      path: /app


  - name: copy the mongo repo 
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: copy the catalogue service 
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: mongo client install
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  - name: connnect to mongodb catalogue
    ansible.builtin.command: mongosh mongodb.bpotla.com  --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
    register: catalogue_output

  - name: load products into mongodb
    ansible.builtin.shell: mongosh --host mongodb.bpotla.com </app/db/master-data.js
    when: catalogue_output.stdout | int < 0 ##Catlogue_output.stdout value is "-1" . which is in string format ,when we keep the condition converting string to int

  # - name: start the mongodb
  #   ansible.builtin.service:
  #     name: catalogue
  #     state: started
  #     enabled: yes

  # - name: Reload systemd daemon
  #   ansible.builtin.systemd_service:
  #     daemon_reload: true


  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: catalogue
      enabled: true
      state: started
      daemon_reload: true
