---
- name: EC2 and Route 53
  hosts: local
  connection: local
  # become: yes
  # become_user: root
  vars:
    instances:
    - mongodb
    ami_id: ami-09c813fb71547fc4f
    sg: sg-084ef175a8b117541
    hosted_zone: Z03518071VI2MRRCQX1QH
    domain_name: bpotla.com
  tasks:
  - name: Launch the new t2.micro EC2 Instance
    amazon.aws.ec2_instance:
      name: " {{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg }}"
      image_id: "{{ ami_id }}"
      region: us-east-1
    register: ec2_output
    loop: "{{ instances }}"
  
  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: print public_ip
    ansible.builtin.debug: 
      msg: "{{ item.instances[0].public_ip_address }}"
    loop: "{{ ec2_output.results }}"
    register: pub_output
      
  - name: print pub_output
    ansible.builtin.debug:
      msg: " publicip: {{ pub_output }}"

  - name: print ip address
    ansible.builtin.debug: 
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: route 53 record creation
    amazon.aws.route53:
      state: present
      zone: "{{ hosted_zone }}"
      record: "{{ item }}.{{domain_name}}"
      type: A
      ttl: 1
    register: record_output
    loop: "{{ instances }}"

  - name: print record_output
    ansible.builtin.debug:
      msg: "{{ record_output }}"

    

  
