---
- name: mysql configuration 
  hosts: mysql
  become: yes
  vars: 
  tasks:

  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start the mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: create user and password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
