---
- name: rabbitmq configuration 
  hosts: rabbitmq
  become: yes
  vars: 
  tasks:
 
  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install rabbitmq
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  
  - name: start the rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes
      
  - name: creating the user
    community.rabbitmq.rabbitmq_user:
      user: roboshop 
      password: roboshop123
      permissions:
      - vhost: "/"              # Virtual host
        configure_priv: ".*"    # Configure permissions
        read_priv: ".*"         # Read permissions
        write_priv: ".*"        # Write permissions
      state: present



