---
- name: shipping configuration
  hosts: shipping
  become: yes
  tasks:
  - name: maven install
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql
##install cryptography
  - name: install mysql python libraries
    ansible.builtin.pip:
      executable: pip3.9
      name: "{{ item }}"
    loop:
    - cryptography
    - PyMySQL

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      system: true
      shell: /sbin/nologin
      home: /app

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete catalogue file
    ansible.builtin.file:
      path: /tmp/shipping-v3.zip 
      state: absent

  - name: Download file to destination
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip  
      dest: /tmp/shipping.zip

  - name: extract catalogue zip
    ansible.builtin.unarchive:
      dest: /app
      src: /tmp/shipping.zip
      remote_src: yes

  # - name: mvn clean install
  #   ansible.builtin.shell: |
  #     cd /app 
  #     mvn clean package 
  #     mv target/shipping-1.0.jar shipping.jar

  ##we can write abve command like below 

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: move jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy the shipping service 
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: import shipping data into mysql
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.bpotla.com
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: shipping
      enabled: true
      state: started
      daemon_reload: true
