---
- name: user configuration
  hosts: user
  become: yes
  tasks: 
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      system: true
      shell: /sbin/nologin
      home: /app

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent


  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete user file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent


  - name: Download file to destination
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip 
  
  - name: extract user zip
    ansible.builtin.unarchive:
      dest: /app
      src: /tmp/user.zip
      remote_src: yes

  - name: node js install
    community.general.npm:
      path: /app

  - name: copy the user service 
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: Reload systemd daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start the mongodb
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes
